#!/bin/sh

## Password 'insecure' generated by `from IPython.lib import passwd; passwd()`

ipython3 notebook --allow-root --no-browser --ip=* --port=9527 --NotebookApp.password=sha1:32c361cae23b:f4f89f6e3dfa3a5f263d3c83ab99610195026b20
